---
- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: debian.yml
  when: >
    ansible_os_family == 'Debian' or
    ansible_os_family == 'Parrot GNU/Linux' or
    ansible_os_family == 'Pop!_OS'
