---
- name: Check if Rust is installed
  stat:
    path: "/home/{{ target_user }}/.cargo/bin/rustc"
  register: rustc_bin

- name: Download Rust installer (rustup)
  get_url:
    url: "https://sh.rustup.rs"
    dest: "/tmp/rustup.sh"
  when: not rustc_bin.stat.exists or force is defined

- name: Install Rust using rustup
  script: "/tmp/rustup.sh -y"
  when: not rustc_bin.stat.exists or force is defined

- name: Add Rust to PATH
  blockinfile:
    marker: "# {mark} Rust path"
    dest: "/home/{{ target_user }}/.bashrc"
    content: "source \"$HOME/.cargo/env\""
  when: not rustc_bin.stat.exists or force is defined
