---
- name: Install development tools
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 300
  vars:
    packages:
      - build-essential
      - ninja-build
      - cmake
      - gdb
      - autoconf
      - automake
      - musl-dev
      - musl-tools
      - pinentry-gtk2
      - foodcritic
      - shellcheck

- name: Install Python 3 development tools
  become: yes
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
      - ansible-lint
      - cmakelint
      - flake8
      - vim-vint
