---
- name: Add Firefox PPA
  become: yes
  apt_repository:
    repo: "ppa:mozillateam/firefox-next"
    state: present
    update_cache: yes

- name: Install Firefox
  become: yes
  apt:
    name: "firefox"
    state: latest
    update_cache: yes
    cache_valid_time: 300
