---
- name: Install basic deps
  become: yes
  apt:
    name: "{{ items }}"
    state: present
    update_cache: yes
    cache_valid_time: 300
  vars:
    items:
      - ncdu
      - wget
      - tmux
      - tree
      - xsel
      - build-essential
      - curl
      - jq
      - rxvt-unicode-256color
      - tar
      - unzip
      - zip
      - whois
      - tilix
      - pinentry-gtk2
      - vim
      - htop
      - silversearcher-ag
      - shellcheck
      - aria2
      - gnupg2
      - python-pip
      - python3-pip
