---
- name: Install basic deps
  become: yes
  apt:
    name: "{{ items }}"
    state: present
    update_cache: yes
    cache_valid_time: 300
  vars:
    items:
      - ncdu
      - wget
      - tmux
      - tree
      - xsel
      - curl
      - jq
      - tar
      - unzip
      - zip
      - whois
      - tilix
      - vim
      - htop
      - silversearcher-ag
      - shellcheck
      - aria2
      - gnupg2
      - git
      - git-lfs
      - mtr-tiny
      - ssh
      - cmus
      - python-pip
      - python3-pip
      - ufw
      - p7zip-full
      - libu2f-udev       # U2F support in browsers
      - libu2f-host-dev   # U2F support in browsers
      - bolt              # thunderbolt authorization
      # ubuntu specific
      - build-essential
      - ninja-build
      - unrar

- include_role:
    name: bat

- include_role:
    name: diff-so-fancy

- include_role:
    name: fd

- include_role:
    name: ripgrep

- include_role:
    name: prettyping

- include_role:
    name: git-libsecret

- name: Install minimal desktop programs
  become: yes
  apt:
    name: "{{ items }}"
    state: present
    update_cache: yes
    cache_valid_time: 300
  vars:
    items:
      - rofi
      - imagemagick
      - flameshot
      - pinentry-gtk2
      - thunar
      - thunar-archive-plugin
      - thunar-media-tags-plugin
      - thunar-volman
  when: mindesktop is defined

- name: Install desktop programs
  become: yes
  apt:
    name: "{{ items }}"
    state: present
    update_cache: yes
    cache_valid_time: 300
  vars:
    items:
      - arandr
      - feh
      - pasystray
      - paprefs
      - redshift
      - fcitx
      - fcitx-mozc
      - fcitx-frontend-all
      - fcitx-config-gtk2
      - fcitx-config-gtk
      - ruby
#      - ruby-docs
      - docker
      - xautolock
#      - noto-fonts-emoji
#      - cpupower
      - i3
      - lxappearance
      - numix-gtk-theme
      - numix-icon-theme
      - cifs-utils
      - pcmanfm
      - thunar-gtkhash
  when: desktop is defined

- include_role:
    name: touchpad-configs
  when: desktop is defined

- include_role:
    name: polybar
  when: desktop is defined

- include_role:
    name: google-chrome
  when: desktop is defined
