[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
hook_add = '''
let g:deoplete#enable_at_startup = 1

inoremap <silent><expr> <Tab> pumvisible() ? "\<C-n>" : deoplete#mappings#manual_complete()
inoremap <silent><expr> <S-Tab> pumvisible() ? "\<C-p>" : deoplete#mappings#manual_complete()
'''
on_event = 'InsertEnter'
