---
- name: Check if msgpack is already installed
  stat:
    path: "/usr/local/include/msgpack/version.h"
  register: msgpack

- name: Download and install MessagePack
  git:
    repo: "https://github.com/msgpack/msgpack-c"
    dest: "/tmp/msgpack-c"
    clone: yes
    update: yes
    version: "{{ msgpack_vers }}"
  when: not msgpack.stat.exists

- name: Create MessagePack build folder
  file:
    path: "/tmp/msgpack-c/build"
    state: directory
  when: not msgpack.stat.exists

- name: Configure MessagePack
  shell: "{{ item }} chdir=/tmp/msgpack-c/build"
  with_items:
    - "cmake -DMSGPACK_CXX11=ON -GNinja .."
    - "ninja"
  when: not msgpack.stat.exists

- name: Install MessagePack
  become: yes
  command: "ninja install chdir=/tmp/msgpack-c/build"
  when: not msgpack.stat.exists
