---
- name: Add Wireshark stable PPA
  become: yes
  apt_repository:
    repo: "ppa:wireshark-dev/stable"
    state: present
    update_cache: yes

- name: Install wireshark
  become: yes
  apt:
      name: wireshark
      state: latest
      update_cache: yes
      cache_valid_time: 300
