[[plugins]]
repo = 'Shougo/deoplete.nvim'
if = 'has("python3")'
hook_add = '''
let g:deoplete#enable_at_startup = 1
'''
on_event = 'InsertEnter'

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'
depends = 'deplete.vim'

[[plugins]]
repo = 'tweekmonster/deoplete-clang2'
on_ft = ['c', 'cpp', 'cmake']
depends = 'depolete.vim'
