---
- name: Add i3 keyring
  become: yes
  apt:
    deb: http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2017.01.02_all.deb

- name: Add i3 source
  become: yes
  lineinfile:
    dest: "/etc/apt/sources.list.d/sur5r-i3.list"
    regexp: "^deb http://debian.sur5r.net/i3/ {{ ansible_lsb.codename }} universe$"
    line: "deb http://debian.sur5r.net/i3/ {{ ansible_lsb.codename }} universe"
    create: yes

- name: Install i3
  become: yes
  apt:
      name: i3
      state: latest
      update_cache: yes
      cache_valid_time: 300

- name: Create i3 config folder if necessary
  file:
    path: "/home/{{ ansible_env.USER }}/.config/i3"
    state: directory

- name: Copy i3 config
  copy:
    src: "{{ role_path }}/files/config"
    dest: "/home/{{ ansible_env.USER }}/.config/i3/config"
    force: no
