---
- name: Install Python pre-reqs
  become: yes
  pip:
    name: "{{ packages }}"
    executable: "pip3"
  vars:
    packages:
      - setuptools
      - wheel

- include_tasks: arch.yml
  when: ansible_os_family == 'Archlinux'

- include_tasks: ubuntu.yml
  when: ansible_os_family == 'Debian' or ansible_os_family == 'Parrot GNU/Linux'

- name: Install Python Neovim
  become: yes
  pip:
    name: "{{ packages }}"
    executable: "pip3"
  vars:
    packages:
      - neovim
