---
- name: Install neovim dependencies
  become: yes
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
    cache_valid_time: 400
  vars:
    packages:
      - python3-pip
      - python3-setuptools

- name: Install neovim ppa
  become: yes
  apt_repository:
    repo: "ppa:neovim-ppa/{{ neovim_ppa_type }}"
    update_cache: yes
  when: ansible_os_family == 'Debian'

- name: Install neovim
  become: yes
  apt:
    name: neovim
    state: present
    update_cache: yes
    cache_valid_time: 400
