---
- name: Install tmux
  become: yes
  apt:
    pkg: tmux
    state: latest
    update_cache: yes
    cache_valid_time: 300

- name: Copy tmux configurations
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "/home/{{ ansible_env.USER }}/.tmux.conf"
