---
    - name: Install vim & gvim
    pacman: name=vim-gtk
            state=latest
    sudo: yes

    - name: Setup NeoBundle
    git: repo=https://github.com/Shougo/neobundle.vim
        dest={{ "~/.vim/bundle/neobundle.vim" | expanduser }}
        update=yes

    - name: Copy .vimrc file
    copy: src=../vim/vimrc
        dest={{ "~/.vimrc" | expanduser }}

    - name: Copy vim custom and plugin configs
    copy: src=../vim/vim/
        dest={{ "~/.vim/" | expanduser }}
