---
- name: Find the latest release
  uri:
    url: "https://api.github.com/repos/sharkdp/fd/releases/latest"
    return_content: true
  register: json_output

- name: Extract latest fd version
  set_fact:
    fd_version: "{{ json_output.json.tag_name | regex_replace('^v(.*)', '\\1') }}"

- name: "Install fd {{ fd_version }}"
  become: yes
  apt:
    deb: "https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd_{{ fd_version }}_amd64.deb"
