---
- name: Add Numix PPA
  become: yes
  apt_repository:
    repo: "ppa:numix/ppa"
    state: present
    update_cache: yes

- name: Install Numix themes
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 300
  with_items:
    - numix-gtk-theme
    - numix-icon-theme
    - numix-icon-theme-circle
    - numix-icon-theme-square
