---
- name: Check if Android Studio is installed
  stat:
    path: "/home/{{ ansible_env.USER }}/android-studio"
  register: android_studio_is_installed

- name: Install Android Studio
  unarchive:
    src: "https://dl.google.com/dl/android/studio/ide-zips/{{ android_studio_file }}"
    dest: "/home/{{ ansible_env.USER }}/android-studio"
    remote_src: True
  when: not android_studio_is_installed.stat.exists

- name: Add Android Studio to PATH
  blockinfile:
    dest: "/home/{{ ansible_env.USER }}/.bashrc"
    marker: "# {mark} Android Studio Environment"
    state: present
    content: |
      export PATH=$PATH:$HOME/android-studio/bin
      export PATH=$PATH:$HOME/Android/Sdk/platform-tools

- name: Create Android Studio Desktop file
  blockinfile:
    dest: "/home/{{ ansible_env.USER }}/.local/share/applications/android-studio.desktop"
    create: yes
    state: present
    content: |
      [Desktop Entry]
      Exec=bash -i -c /home/{{ ansible_env.USER }}/android-studio/bin/studio.sh
      Icon=/home/{{ ansible_env.USER }}/android-studio/bin/studio.png
      Type=Application
      Terminal=false
      Name=Android Studio
      GenericName=Integrated Development Environment
      MimeType=text/x-c++src;text/x-c++hdr;text/x-xsrc;application/x-designer;
      Categories=Android;Development;IDE;
      InitialPreference=2
