---
- src: git+https://github.com/r2dkennobi/bat-ansible
  version: master
- src: git+https://github.com/r2dkennobi/prettyping-ansible
  version: master
- src: git+https://github.com/r2dkennobi/diff-so-fancy-ansible
  version: master
- src: git+https://github.com/r2dkennobi/rust-ansible
  version: master
- src: git+https://github.com/r2dkennobi/fd-ansible
  version: master
- src: git+https://github.com/r2dkennobi/vim-ansible
  version: master
- src: git+https://github.com/r2dkennobi/neovim-ansible
  version: master
