---
- name: All the vim
  hosts: all
  tasks:
    - include_role:
        name: vim
    - include_role:
        name: neovim
    - name: Clone vim configurations
      git:
        repo: "https://github.com/r2dkennobi/.vim.git"
        dest: "$HOME/.vim"
    - name: Link .vimrc
      file:
        src: "$HOME/.vim/.vimrc"
        dest: "$HOME/.vimrc"
        state: link
        force: true
    - name: Clone neovim configurations
      git:
        repo: "https://github.com/r2dkennobi/nvim.git"
        dest: "$HOME/.config/nvim"
    - name: Additional apt packages for syntax checking in neovim
      become: yes
      apt:
        name: "{{ items }}"
        state: present
        update_cache: yes
        cache_valid_time: 300
      vars:
        items:
          - foodcritic
          - shellcheck
      when: ansible_os_family == 'Debian' or ansible_os_family == 'Parrot GNU/Linux'
    - name: Additional python packages for syntax checking in neovim
      become: yes
      pip:
        name: "{{ packages }}"
        executable: "pip3"
      vars:
        packages:
          - ansible-lint
          - cmakelint
          - flake8
          - vim-vint
