---
- name: Find the latest release
  uri:
    url: "https://api.github.com/repos/BurntSushi/ripgrep/releases/latest"
    return_content: true
  register: json_output

- name: Extract latest ripgrep version
  set_fact:
    rg_version: "{{ json_output.json.tag_name | regex_replace('^v(.*)', '\\1') }}"

- name: "Install ripgrep {{ rg_version }}"
  become: yes
  apt:
    deb: "https://github.com/BurntSushi/ripgrep/releases/download/{{ rg_version }}/ripgrep_{{ rg_version }}_amd64.deb"
