---
- name: Install screen
  become: yes
  apt:
      name: screen
      state: latest
      update_cache: yes
      cache_valid_time: 300

- name: Copy screen configurations
  copy:
    src: "{{ role_path }}/files/screenrc"
    dest: "/home/{{ ansible_env.USER }}/.screenrc"
