---
- name: Check if install is necessary
  stat:
    path: "/usr/local/bin/ctags"
  register: universal_ctags_bin

- name: Clone latest universal-ctags
  git:
    repo: "https://github.com/universal-ctags/ctags"
    dest: "{{ build_dir }}/universal-ctags"
  when: not universal_ctags_bin.stat.exists or force is defined

- name: Configure universal-ctags
  shell: "{{ item }} chdir={{ build_dir }}/universal-ctags"
  with_items:
    - "./autogen.sh"
    - "./configure"
    - "make"
  when: not universal_ctags_bin.stat.exists or force is defined

- name: Install universal-ctags
  become: yes
  become_user: root
  command: "make install chdir={{ build_dir }}/universal-ctags"
  when: not universal_ctags_bin.stat.exists or force is defined
