---
- name: Add latest Neovim PPA
  become: yes
  apt_repository:
    repo: "ppa:neovim-ppa/stable"
    state: present
    update_cache: yes

- name: Install Neovim
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 300
  with_items:
    - neovim
    - python3-pip

- name: Make sure Neovim config folder exists
  file:
    path: "/home/{{ ansible_env.USER }}/.config/nvim"
    state: directory

# Mmm...recursive copy not working as expected
- name: Copy configurations
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "/home/{{ ansible_env.USER }}/.config/nvim/{{ item }}"
  with_items:
    - init.vim
    - dein.toml
    - dein_lazy.toml

- name: Install Ale deps via apt (for syntax checking)
  become: yes
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
    cache_valid_time: 300
  with_items:
    - foodcritic
    - shellcheck

- name: Install Ale deps via pip (for syntax checking)
  become: yes
  pip:
    name: "{{ item }}"
    state: latest
  with_items:
    - ansible-lint
    - cmakelint
    - flake8
    - vim-vint

- name: Install Neovim for python3
  become: yes
  pip:
    name: neovim
    executable: pip3
    state: latest
