---
- name: Check if capnproto is already installed
  stat:
    path: "/usr/local/include/capnp/common.h"
  register: capnproto

- name: "Download and install Cap'n Proto"
  unarchive:
    src: "https://capnproto.org/capnproto-c++-{{ capnproto_vers }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/capnproto-c++-{{ capnproto_vers }}"
    keep_newer: yes
    remote_src: True
  when: not capnproto.stat.exists

- name: "Create Cap'n Proto build folder"
  file:
    path: "/tmp/capnproto-c++-{{ capnproto_vers }}/build"
    state: directory
  when: not capnproto.stat.exists

- name: "Configure Cap'n Proto"
  shell: "{{ item }} chdir=/tmp/capnproto-c++-{{ capnproto_vers }}/build"
  with_items:
    - "cmake -GNinja .."
    - "ninja"
  when: not capnproto.stat.exists

- name: "Install Cap'n Proto"
  become: yes
  command: "ninja install chdir=/tmp/capnproto-c++-{{ capnproto_vers }}/build"
  when: not capnproto.stat.exists
